### PR TITLE
add anshook to run a function on returned values in cells

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by KristofferC** [comment]
cc @stevengj

**Comment by stevengj** [comment]
LGTM, thanks.

**Comment by KristofferC** [comment]
Could you perhaps tag a release with this?

**Comment by stevengj** [comment]
Just tagged 1.2.0

**Comment by stevengj** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/9517

**Pull request merged**
